General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
MFW:
    db_in_flag: 'csv' # csv, sqlite, mysql
    db_out_flag: 'csv' # csv, sqlite, mysql