General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
TripAdvisor:
    db_in_flag: False
    db_out_flag: False