General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
TripAdvisor:
    db_in_flag: csv # csv, mysql, sqlite
    db_out_flag: csv # csv, mysql, sqlite
    earliest_date: 01-01-2000 # dd-mm-yyyy or None. Higher priority than number_of_pages.
    number_of_pages: 5 # int or None.
