General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
TripAdvisor:
    read_from_database: csv  # mysql, sqlite or csv
    write_to_database: csv  # mysql, sqlite or csv
    start_page:  # int or None
    earliest_date:  # dd-mm-yyyy or None. Higher priority than number_of_pages.
    number_of_pages:  # int or None. if 0, only Attributes are crawled.
    csv_folder:  # in the format yyymmdd_hhmmss
