General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
TripAdvisor:
    csv_input_path: ./tripadvisor/20191208_attractions_list.csv
    read_from_database: csv  # mysql, sqlite or csv
    write_to_database: csv  # mysql, sqlite or csv
    start_page:  # int or None
    earliest_date: 01-01-2016  # dd-mm-yyyy or None. Higher priority than number_of_pages.
    number_of_pages:  # int or None. if 0, only Attributes are crawled.
    target_folder: '200126_094431'  # in the format yyymmdd_hhmmss, in quotes to preserve '_'
