---
title: "Descriptive Stats (TripA)"
author: "Zheng Yifei"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("ggplot2")
```

```{r}
folder_list <-list.files("./finalised_output")
folder_list
```

```{r}
reviews_df <- read.csv("./finalised_output/200125_142611/reviews/1.csv", as.is = TRUE)

for (i in c(2, 3, 7, 11)) {
    reviews_df[,i] <- as.factor(reviews_df[,i])
}

reviews_df[,6] <- lubridate::parse_date_time(reviews_df[,6], orders=c("dmy"))
reviews_df[,10] <- lubridate::parse_date_time(reviews_df[,10], orders=c("my"))
reviews_df[,12] <- lubridate::parse_date_time(reviews_df[,12], orders=c("ymdHMS"))

reviews_df <- reviews_df[,3:12]

reviews_df$MONTH_OF_EXPERIENCE <- as.factor(format(reviews_df$DATE_OF_EXPERIENCE, format="%m"))
reviews_df$YEAR_OF_EXPERIENCE <- as.factor(format(reviews_df$DATE_OF_EXPERIENCE, format="%Y"))

head(reviews_df)
```

```{r}
summary(reviews_df)
```

```{r}
GGally::ggpairs(reviews_df[,c(4, 5, 9, 11, 12)])
```

```{r}
ggplot(reviews_df, aes(DATE_OF_EXPERIENCE)) + geom_bar()
```

```{r}

```

