General:
    host: localhost
    database: sentimentDB
    user: test_user
    password: Password123!
    chromedriver_path: ./chromedriver
    
Ctrip:
    csv_input_path: ./ctrip_list.csv
    read_from_database: csv  # mysql, sqlite or csv
    write_to_database: csv  # mysql, sqlite or csv
    number_of_pages: 0 # int or None. if 0, only Attributes are crawled. number of pages per POI
    proxy_mode: 2 #1:SG, 2: SG->proxy; 3: proxy
    timeout: 120 #in seconds, stop loading after limit reached. If None, always complete loading 
    authen_count: 3 #reload time to test whether authentication error exist or not. Min 1
    
